import { customOrderLeatherColor } from "~/lib/custom-order/values/custom-order-leather-color"
import { customOrderLeatherType } from "~/lib/custom-order/values/custom-order-leather-type"

export const customOrderLeatherColorMap = new Map([
  [
    customOrderLeatherType.embossed01,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.embossed02,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.embossed03,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.embossed04,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.embossed05,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.ostrichSkin,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
    ],
  ],
  [
    customOrderLeatherType.kipskin,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.crocodileBack,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
    ],
  ],
  [
    customOrderLeatherType.crocodileBelly,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
    ],
  ],
  [
    customOrderLeatherType.suede,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
    ],
  ],
  [
    customOrderLeatherType.scotchGrain,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.blue,
    ],
  ],
  [
    customOrderLeatherType.deerSkin,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
    ],
  ],
  [
    customOrderLeatherType.baron,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.darkBrown,
      customOrderLeatherColor.lightBrown,
      customOrderLeatherColor.blue,
      customOrderLeatherColor.wineRed,
      customOrderLeatherColor.antiqueGray,
    ],
  ],
  [
    customOrderLeatherType.boxCalf,
    [customOrderLeatherColor.black, customOrderLeatherColor.darkBrown],
  ],
  [
    customOrderLeatherType.waterproofCalf,
    [
      customOrderLeatherColor.black,
      customOrderLeatherColor.white,
      customOrderLeatherColor.green,
      customOrderLeatherColor.gray,
    ],
  ],
])
