#:schema ../node_modules/wrangler/config-schema.json

name = "uninoverse"
compatibility_date = "2024-09-09"
main = "index.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[services]]
binding = "API"
service = "uninoverse-console-api"

[[routes]]
pattern = "uninoverse.dev"
custom_domain = true
