name: Deploy - Webhooks

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - webhooks/**

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: 👩‍💻 チェックアウト
        uses: actions/checkout@v4
      - name: 🔨 Bunを有効にする
        uses: oven-sh/setup-bun@v1
      - name: 🔨 インストール
        run: bun install
      - name: 🚀 ビルド&デプロイ
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy index.ts --name=uninoverse-webhooks
          workingDirectory: webhooks
