# Don't change the line below!
#! oxygen_storefront_id: 1000014458

name: Storefront 1000014458

on:
  workflow_dispatch:
  push:
    paths:
      - hydrogen/**

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: 🔨 Checkout!
        uses: actions/checkout@v4
      - name: 🔨 Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: 🔨 Install
        run: bun install --ignore-scripts
      - name: 💪 Build and Publish to Oxygen
        run: bun run --cwd hydrogen deploy
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000014458 }}
